name: CI / Publish web

on:
  workflow_dispatch:

env:
  NODE_VERSION: 22.x

jobs:
  tests:
    name: ðŸ§ª Tests
    secrets: inherit
    uses: ./.github/workflows/tests.yml

  publish:
    name: ðŸš€ Publish web
    runs-on: ubuntu-latest
    environment: Production
    needs: [tests]
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v5

      - name: ðŸ”¨ Setup
        uses: ./tooling/github/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ðŸ”¼ Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: ðŸ’ª Pull environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: ðŸ“¦ Build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: ðŸ’¨ Publish!
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
