name: CI / Publish mobile

on:
  workflow_dispatch:

env:
  NODE_VERSION: 22.x

jobs:
  tests:
    name: ğŸ§ª Tests
    secrets: inherit
    uses: ./.github/workflows/tests.yml

  publish:
    name: ğŸš€ Publish mobile
    runs-on: ubuntu-latest
    environment: Production
    needs: [tests]
    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v5

      - name: ğŸ”¨ Setup
        uses: ./tooling/github/setup
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ’¨ Publish!
        run: cd apps/mobile && eas build --platform all --profile production --non-interactive --no-wait --auto-submit
